---
version: '1.0.0-b{build}'

configuration:
  - Release

platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build "src\SampleWebApiAspNetCore" -c %CONFIGURATION% --no-dependencies

after_build:
  - dotnet publish "src\SampleWebApiAspNetCore" -c %CONFIGURATION% --no-build --version-suffix b%APPVEYOR_BUILD_NUMBER% -o "artifacts\SampleWebApiAspNetCore"

artifacts:
  - path: artifacts\SampleWebApiAspNetCore

cache:
  - '%USERPROFILE%\.nuget\packages'

build:
  publish_wap: true

deploy:
  - provider: WebDeploy
    server: http://websitezz4rsd3bbmqha.azurewebsites.net/
    website: websitezz4rsd3bbmqha
    username: ok-deploy
    password:
      secure: MBRjbxvDb/L+8o7AXene8A==
    aspnet_core: true
