---
version: '1.0.0-b{build}'

configuration:
  - Debug
  - Release

platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build "src\*" -c %CONFIGURATION% --no-dependencies

after_build:
  - dotnet publish "src\*" -c %CONFIGURATION% --no-build --version-suffix b%APPVEYOR_BUILD_NUMBER% -o artifacts

artifacts:
  - path: artifacts\**\*.*

cache:
  - '%USERPROFILE%\.nuget\packages'
