---
version: '1.0.0-b{build}'

configuration:
  - Release

platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build "src\SampleWebApiAspNetCore" -c %CONFIGURATION% --no-dependencies

after_build:
  - dotnet publish "src\SampleWebApiAspNetCore" -c %CONFIGURATION% --no-build --version-suffix b%APPVEYOR_BUILD_NUMBER% -o "C:\projects\aspnet-core-webapi-sample\artifacts\SampleWebApiAspNetCore"

artifacts:
  - path: artifacts\SampleWebApiAspNetCore

cache:
  - '%USERPROFILE%\.nuget\packages'

deploy:
  - provider: WebDeploy
    server: https://websitezz4rsd3bbmqha.scm.azurewebsites.net/msdeploy.axd?site=webSitezz4rsd3bbmqha
    website: webSitezz4rsd3bbmqha
    username: ok-deploy
    password:
      secure: MBRjbxvDb/L+8o7AXene8A==
    aspnet_core: true
    aspnet_core_force_restart: true
    app_offline: true
    ntlm: false
